import { apiClient } from './apiClient';
import type { Notification, NotificationType } from '../types';

/**
 * Real notifications client backed by core.notifications through the backend
 * (`/api/v1/notifications`). Rows are generated by database triggers on real
 * platform events (likes, chat messages, system events).
 */
interface ApiEnvelope<T> {
  success: boolean;
  data: T;
}

interface BackendNotification {
  id: number;
  profileId: string;
  type: string;
  title: string;
  message: string;
  isRead: boolean;
  createdAt: string;
}

function mapNotification(raw: BackendNotification): Notification {
  return {
    id: String(raw.id),
    profileId: raw.profileId,
    type: raw.type as NotificationType,
    title: raw.title,
    message: raw.message,
    isRead: raw.isRead,
    createdAt: raw.createdAt,
  };
}

export const notificationsService = {
  async getNotifications(limit = 30): Promise<Notification[]> {
    const { data } = await apiClient.get<ApiEnvelope<BackendNotification[]>>('/v1/notifications', {
      params: { limit },
    });
    return (data.data ?? []).map(mapNotification);
  },

  async markAsRead(notificationId: string): Promise<void> {
    await apiClient.patch(`/v1/notifications/${notificationId}/read`);
  },

  async markAllAsRead(): Promise<void> {
    await apiClient.post('/v1/notifications/read-all');
  },
};
